name: CI/CD MLflow

on:
  push:
    branches: [ main ]

env:
  CSV_URL: "MLProject/preprocessed_data.csv"
  TARGET_VAR: "Exam_Score"

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlflow-env
        auto-activate-base: false

    - name: Init Conda
      run: |
        conda init bash
        source ~/.bashrc

    - name: Install Dependencies
      run: |
        source ~/.bashrc
        conda activate mlflow-env
        pip install mlflow
        pip install -r MLProject/requirements.txt

    - name: Run MLflow Project
      run: |
        source ~/.bashrc
        conda activate mlflow-env
        cd MLProject
        mlflow run . -P data_path=preprocessed_data.csv --env-manager=local

    - name: Get run_id
      run: |
        RUN_ID=$(ls -td MLProject/mlruns/0/*/ | head -n 1 | cut -d'/' -f4)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # 🔥 DEBUG (biar gak error lagi)
    - name: Debug artifacts
      run: |
        echo "Isi artifacts:"
        ls -R MLProject/mlruns/0/$RUN_ID/

    # 🔥 VERIFY (lebih fleksibel)
    - name: Verify artifacts exist
      run: |
        if [ ! -d "MLProject/mlruns/0/$RUN_ID/artifacts" ]; then
          echo "Artifacts not found!"
          exit 1
        fi

    - name: Push mlruns
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
        git add MLProject/mlruns
        git commit -m "Update mlruns" || echo "No changes"
        git push

    # 🔥 BUILD DOCKER (nama konsisten)
    - name: Build Docker
      run: |
        mlflow models build-docker \
        --model-uri "file://$GITHUB_WORKSPACE/MLProject/mlruns/0/$RUN_ID/artifacts/model" \
        --name student-performance-model

    - name: Login Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Image
      run: |
        docker tag student-performance-model ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance-model:latest

    - name: Push Docker
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-performance-model:latest
